### ISSUE TITLE
Free author when UI is disabled

### ISSUE THREAD

**Issue by bastian-lengen-epfl** [GreepTheSheep/openplanet-mx-random#16]
One of my friend and me noticed that we could "win" an author medal without actually beating the time. What we notice is that, if you disabled the UI at the begining of the run and never re-activate it, once you cross the finish the map is skipped and you earn a goldmap.

**Comment by GreepTheSheep** [comment]
Hey, can you add more details, like what is the Author and Gold times on a map, and what time did he finished? Thanks :)

**Comment by Bligoubloups** [comment]
Hello, Yannex just got similar bug.
https://www.twitch.tv/videos/1160814796?t=4h14m42s

**Comment by GreepTheSheep** [comment]
@Bligoubloups yep i'm aware for this one and it's explained in #21, it's fixed that's why it's closed. But now I got a major bug explained in #23, when this major bug is fixed, an update will be pushed asap

**Comment by GreepTheSheep** [comment]
Seems like this issue can not be reproduced, seems a duplicate of #21 (fixed 2 months ago), i'll close this issue for inactivity
