### ISSUE TITLE
Add option for Gold challenge for begginer players

### ISSUE THREAD

**Issue by pmanacas** [GreepTheSheep/openplanet-mx-random#17]
I think it would be great to have an option to set Gold Medal as target instead of Author (with Silver enough for skip).
Thanks!

**Comment by GreepTheSheep** [comment]
Yep will work on that

**Comment by GreepTheSheep** [comment]
Will be pushed on v1.5 👍

**Comment by pmanacas** [comment]
Great news =) thank you
