### ISSUE TITLE
Displaying map info in timer can lose performance

### ISSUE THREAD

**Issue by winkelino** [GreepTheSheep/openplanet-mx-random#18]
If you have a lot of maps in your recently played list, having the current map info displayed in the timer can lose a lot of performance.
I went from 150+ to around 80 FPS by displaying the current map info.
Hiding the map info from the timer or clearing the history regularly can be a workaround for the problem.

**Comment by GreepTheSheep** [comment]
Will be pushed on 1.5 👍
