### ISSUE TITLE
AT is skipped incorrectly

### ISSUE THREAD

**Issue by SteveVanOpstal** [GreepTheSheep/openplanet-mx-random#21]
plugin skips incorrectly in this scrapie clip, seems like it is about a 100ms diff on AT from what I noticed in this and other runs. 

https://clips.twitch.tv/SpotlessLitigiousOrangeKreygasm-6kkoHPeVYdjit6pV

**Comment by GreepTheSheep** [comment]
I'm aware of this, it's said in the changelog:
![image](https://user-images.githubusercontent.com/42576124/134070976-240efde0-a0f3-40a1-88b6-9bdf8868acc6.png)

I'll keep this issue open until we find a solution

**Comment by GreepTheSheep** [comment]
Issue finally fixed, will be pushed on 1.5.1 🎉

**Comment by SteveVanOpstal** [comment]
Ok nice, love the plugin.
Might be nice to add the version in the overlay

**Comment by GreepTheSheep** [comment]
It's on the main window (The TMX Randomizer one)

**Comment by TSlivede** [comment]
Am I correct to assume, that this is the same bug as in this clip?
https://www.twitch.tv/videos/1157922180?t=2h54m55s

**Comment by GreepTheSheep** [comment]
@TSlivede Yes, It's fixed on the latest version ;)
