### ISSUE TITLE
Game crashes when loading a map

### ISSUE THREAD

**Issue by huhenU** [GreepTheSheep/openplanet-mx-random#23]
TM2020 crashes in the loading screen after finding a map (on commit 74afef0).
I'm not too familiar with Openplanet but I'm not seeing anything relevant in the Openplanet.log file sadly, are there crash reports or something saved elsewhere that would be of any help?
[Openplanet.log](https://github.com/GreepTheSheep/openplanet-mx-random/files/7210261/Openplanet.log)

**Comment by GreepTheSheep** [comment]
still crashes ? haven't tested on this commit yet. Kinda bad because the log says nothing. It is possible to record another evidence and including the logs please ? Thanks in advance 👍

**Comment by GreepTheSheep** [comment]
> are there crash reports or something saved elsewhere that would be of any help?
Crash reports may be in the Documents\Trackmania\LogCrash folder

**Comment by GreepTheSheep** [comment]
Fixed on 1.6 🎉
