### ISSUE TITLE
RMC could be more competitive

### ISSUE THREAD

**Issue by puttehi** [GreepTheSheep/openplanet-mx-random#25]
## Problem

Currently the RMC seems to look for maps with max 5 minutes length without considering competitiveness.

This means that if you are unlucky, you might get only 5 minute maps and have zero chance at making records.

## Solution

This could be improved by searching all the maps in advance, with say, e.g. a 1 or 2 minute max length and then search for a big pile of maps (say, 200) which would then be fitted into 1 hour and the rest of the maps discarded to produce a pool of maps to be played.

So in the end the total map pool to be played in the challenge will total to 1 hour in race length (total length of challenge).

Then people wouldn't have to mald when they lost the new RMC WR to RNG.

[Here's a link to a possible algorithm to use with example code](https://www.geeksforgeeks.org/subset-sum-problem-dp-25/).

**Comment by GreepTheSheep** [comment]
Hi, unfortunately I'll not working on that. The reason is the Random Map Challenge has the "Random" in the name, that means all can happen during this challenge. So I'm sorry but no, I'll not implementing this thing. Thanks for understanding!
