### ISSUE TITLE
Timer-pause does weird things

### ISSUE THREAD

**Issue by Phlarx** [GreepTheSheep/openplanet-mx-random#32]
On Wirtual's stream:

- Timer paused for some unknown reason
- Clicking the pause button repeatedly made the timer show strange numbers.

Clip: https://clips.twitch.tv/ThankfulZealousRatImGlitch-S35B_7q00LtX20Hk

**Comment by GreepTheSheep** [comment]
Since this bug is a very rare bug (1 month passed and still no reports about that), I need a lot of people that can reproduce this bug and if possible send a video and logs about that, thanks in advance
