### ISSUE TITLE
No skip after author medal

### ISSUE THREAD

**Issue by Enjoydafunk** [GreepTheSheep/openplanet-mx-random#34]
Hey ! 
I've activated "no skip after author medal, and when i got it, my author medal is counted, but i still can "Skip and take gold medal" ! and get a "free" gold medal

**Comment by GreepTheSheep** [comment]
Fixed in commit [19f7c1c](https://github.com/GreepTheSheep/openplanet-mx-random/commit/19f7c1cf1b29c817c4ee6af62bb16f37d6a885be)
