### ISSUE TITLE
[support] Please help me get this running in "development mode"?

### ISSUE THREAD

**Issue by ZaLiTHkA** [GreepTheSheep/openplanet-mx-random#40]
greetings.. I would like to contribute to this project, but I'm battling to get started with it.

I'm a web developer myself, so Angelscript is a new one to me... but looking through examples and reading the AS documentation, it seems straight forward enough.

---

that said, I've cloned this project into `C:\Users\<username>\Openplanetnext\Plugins\MXRandomizer`, but the Openplanet "logs" view in TM2020 shows the following errors:

* No signature available for file 'info.toml'
* The plugin 'MXRandomizer' is missing (or has an invalid) info.toml file!

please tell me, how can I get this plugin loading from source code? 😕

**Comment by GreepTheSheep** [comment]
There errors shows that you need to have Club edition of the game, as said in CONTRIBUTING.md: 
```
⚠ If you're cloning on Trackmania Next, make sure that you're running the Club edition of the game.
```
https://openplanet.nl/next/club

**Comment by ZaLiTHkA** [comment]
ah, alrighty.. I've only got Standard Access, so that makes sense. thanks for clarifying. pity that means I can't contribute anything though....

I _really_ wanted to move the "track length" and "track style" selections from the Settings window to the normal one, it's ridiculously unintuitive the way it currently works. but anyways, such is life I guess. (:

**Comment by GreepTheSheep** [comment]
oh, this thing is easy to do, I can do it
