### ISSUE TITLE
Survival challenge timer behaviour when skipping with <2min left

### ISSUE THREAD

**Issue by jh0ker** [GreepTheSheep/openplanet-mx-random#42]
I've been watching Scrapie play the Survival challenge and he frequently complains about a percieved "bug" in the plugin behaviour when skipping a map with less than 2 minutes left on the timer.

Specifically, he describes that if you skip a map with less than 2 minutes left on your timer, the timer resets to exactly 2 minutes, thus invalidating the run by giving you extra time. I have observed once myself, when he did it on accident.

Today it happened again, so on a whim i looked if this plugin was open source (it was 👍) and took a quick look at the source code. I'm not very familiar with AngelScript, but it seems to me that this line in the cause:
https://github.com/GreepTheSheep/openplanet-mx-random/blob/main/src/TimerUI.as#L318

Could you clarify if this is actually the intended behaviour? If so, perhaps it would be good to document this on the info page at https://flinkblog.de/RMC/ to prevent this misunderstanding in the future. Otherwise, i believe it should suffice to simply remove the line i linked.

Cheers

**Comment by GreepTheSheep** [comment]
Thanks, I understand now more that thing now, will update that asap
