### ISSUE TITLE
Timer ends on skip

### ISSUE THREAD

**Issue by TimBeyer** [GreepTheSheep/openplanet-mx-random#44]
I was reviewing yesterday's release PR and came across these lines:

https://github.com/GreepTheSheep/openplanet-mx-random/blob/92509578cedb4d4450830a88345a84492295ba78/src/TimerUI.as#L122-L123

If I read this right, the `skipSavedTime` will always be set to `(timer*60*1000)` when the timer is started.

That would then mean that in

https://github.com/GreepTheSheep/openplanet-mx-random/blob/92509578cedb4d4450830a88345a84492295ba78/src/TimerUI.as#L320-L322

the `endTime` gets set to that same value, immediately making it smaller than `startTime`.

Thus this condition would trigger and the run would end:

https://github.com/GreepTheSheep/openplanet-mx-random/blob/92509578cedb4d4450830a88345a84492295ba78/src/TimerUI.as#L143-L154

I don't have access to TM right now to check it, but was wondering if I'm reading this wrong and maybe to see if some code comments could be added to document the purpose of `skipSavedTime` and the exact logic of it.

**Comment by TizianTitus** [comment]
you are probably right, lars skipped today and it ended. 
clip: https://clips.twitch.tv/AgreeableKindFungusResidentSleeper-9RWon5iwkgFFetpe

**Comment by GreepTheSheep** [comment]
I'm trying to do the addition on #38 but did not worked, so I let that aside and pushed with that. On my side, skipping will not end the timer but let as it is. So yeah, big priority on that rn
