### ISSUE TITLE
Error when installed next to ManiaExchange plugin

### ISSUE THREAD

**Issue by larskn** [GreepTheSheep/openplanet-mx-random#51]
When both MXRandom (2.0.3) and ManiaExchange (1.0.4) are installed, there is an error when loading MXRandom. When I uninstall ManiaExchange, MXRandom loads fine.

I'm not sure if this is an issue with MXRandom or ManiaExchange, but I decided to report it here since it seems to be the 2.0 update that caused the error.

![image](https://user-images.githubusercontent.com/6009652/155395841-035c174e-ea58-43e7-ad03-d36154f87949.png)
![image](https://user-images.githubusercontent.com/6009652/155395862-ef2cb35a-5b15-47f5-b338-b2eb4d1cd5d4.png)

**Comment by GreepTheSheep** [comment]
Recently Updated ManiaExchange, I'll let this open to see if it was updated

**Comment by larskn** [comment]
Yep, just saw it and updated. This seems to be fixed, but now I get this error from ManiaExchange:

![image](https://user-images.githubusercontent.com/6009652/155397163-f032a58d-97fb-42fc-b264-43eafac92996.png)

**Comment by GreepTheSheep** [comment]
Seems weird, can you "Restart Script Engine" though the "Developer" menu?

**Comment by larskn** [comment]
Just tested and this new error seems to have nothing to with MXRandom.
It occurs also after I uninstalled MXRandom and did "Restart Script engine". Maybe it conflicts with another plugin? Here is the full log:

![image](https://user-images.githubusercontent.com/6009652/155398210-403c16d8-8e72-4cdc-aff1-4b6d172c7530.png)

Should I try uninstalling the other plugins one by one?

**Comment by GreepTheSheep** [comment]
That's a bug on my side. I'll edit it asap

**Comment by GreepTheSheep** [comment]
Updated ManiaExchange to 1.0.6, fixes that crash

**Comment by larskn** [comment]
Now everything is looking good. Thank you 😃

**Comment by GreepTheSheep** [comment]
Thanks :)
